version: 2.1

jobs:
  build-and-test:
    parameters:
      jdk:
        type: string
    docker:
      - image: cimg/openjdk:<< parameters.jdk >>
    resource_class: small
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - when:
          condition:
            equal: [ "8.0", << parameters.jdk >> ]
          steps:
            - run: mvn jacoco:report coveralls:report

workflows:
  build:
    jobs:
      - build-and-test:
          matrix:
            parameters:
              jdk: ["8.0", "11.0", "17.0", "21.0"]
